/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myffmpeg4android_utils_FFmpegNative */

#ifndef _Included_FFmpegNative
#define _Included_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL native_avcodec_find_decoder
  (JNIEnv *, jobject, jint);

/*
 * Method:    avcodec_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL native_vcodec_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
